# Generated by Django 5.2.6 on 2025-10-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Введите название заголовок",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержимое",
                        null=True,
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото",
                        null=True,
                        upload_to="blog/photo/",
                        verbose_name="Фото",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("publication_at", models.BooleanField(default=True)),
                ("sum_view", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блог",
                "ordering": ["heading"],
            },
        ),
    ]
