# Generated by Django 5.2.6 on 2025-10-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="sum_view",
            new_name="view_count",
        ),
    ]
