# Generated by Django 4.2.2 on 2025-10-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null="True", verbose_name="Token"
            ),
            preserve_default="True",
        ),
    ]
