# Generated by Django 5.2.6 on 2025-10-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
    ]
