# Generated by Django 4.2.2 on 2025-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price"],
                "permissions": [
                    ("can_edit_product", "Can edit product"),
                    ("can_unpublish_product", "Can unpublish product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
